name: multi-sample-factory
channels:
  - defaults
dependencies:
  - pip:
    - numpy>=1.18.1
    - torch>=1.6
    - gym>=0.17.1
    - tensorboard>=1.15.0
    - tensorboardx>=2.0
    - psutil>=5.7.0
    - threadpoolctl>=2.0.0
    - colorlog
    - faster-fifo>=1.0.9
    - filelock
    - opencv-python
    - mlagents-envs>=0.26,<0.27
    - gym-unity>=0.26,<0.27
